Repository music-encoding/music-encoding, pull requests merged in 2018-06, with the labels that each got.

#531 New: Build Guidelines with Travis
  .travis.yml
  build.sh
  deploy-docs.sh
  utils/schematron/ExtractSchFromRNG-2.xsl
  utils/schematron/ExtractSchFromXSD-2.xsl
  utils/schematron/iso_abstract_expand.xsl
  utils/schematron/iso_dsdl_include.xsl
  utils/schematron/iso_svrl_for_xslt2.xsl
Labels: Component: Guidelines & Documentation, Component: Tools, Priority: High, Status: Needs Review, Type: Feature Request

#530 Rename break elements
  source/modules/MEI.shared.xml
Labels: Component: Guidelines & Documentation, Priority: Medium, Status: Needs Decision, Type: Administration

#532 Fixed: Link to Commit
  deploy-docs.sh
Labels: Component: Guidelines & Documentation, Priority: High, Status: Needs Review, Type: Bug

#535 fixed duplicate ids
  source/mei-source.xml
Labels: Component: Core Schema, Priority: High, Status: Needs Work, Type: Bug
