Repository music-encoding/music-encoding, pull requests merged in 2020-10, with the labels that each got.

#719 make mRest and multiRest part of att.color
  source/modules/MEI.visual.xml
Labels: Status: Ready To Merge

#708 Remove explicit mei_ prefix so elements get listed in HTML documentation
  source/modules/MEI.midi.xml
  source/modules/MEI.usersymbols.xml
Labels: Status: Ready To Merge

#698 Add schematron rules for dur.quality values.
  source/modules/MEI.mensural.xml
Labels: Status: Ready To Merge

#658 make clef part of visualOffset
  source/modules/MEI.visual.xml
Labels: Status: Ready To Merge

#655 split and extend modes
  source/modules/MEI.xml
Labels: Status: Ready To Merge

#646 Support tempo text with extension lines
  source/modules/MEI.shared.xml
Labels: Status: Ready To Merge

#626 Improve multiRest
  source/modules/MEI.visual.xml
Labels: Status: Ready To Merge

#703 Allow 100% with trailing fractional zeroes
  source/modules/MEI.xml
Labels: Status: Needs Decision

#681 Move rotate attribute to att.coordinated
  source/modules/MEI.facsimile.xml
  source/modules/MEI.shared.xml
Labels: Component: Core Schema, Status: Ready To Merge, Type: Feature Request

#693 Fix: Dots valid position within MEI file.
  customizations/mei-Mensural.xml
  source/modules/MEI.shared.xml
Labels: Status: Needs Discussion, Status: Ready To Merge

#720 split data.ACCIDENTAL.WRITTEN and add turkish accidentals
  source/modules/MEI.xml
Labels: Status: Needs Decision, Status: Ready To Merge

#723 Add fermata attribute for mensural notes
  source/modules/MEI.analytical.xml
  source/modules/MEI.mensural.xml
Labels: Status: Ready To Merge

#722 Add plica element & fix stem element
  source/modules/MEI.mensural.xml
  source/modules/MEI.shared.xml
Labels: Status: Ready To Merge

#618 New: Add division element to neumes module
  source/modules/MEI.neumes.xml
Labels: Status: Needs Decision
