Repository music-encoding/music-encoding, pull requests merged in 2021-03, with the labels that each got.

#779 Fixed: Globs on PR configuration
  .github/pr-labeler_config.yml
Labels: Component: Workflows, Priority: Medium, Status: Needs Review, Type: Bugfix

#728 remove empty att.midi.vis
  source/modules/MEI.midi.xml
  source/modules/MEI.visual.xml
Labels: Component: Core Schema, Status: Needs Decision

#726 Update pattern for humdrum recip values
  source/modules/MEI.gestural.xml
Labels: Component: Core Schema, Status: Ready To Merge, Type: Bugfix

#780 remove unnecessary comment
  utils/guidelines_xslt/odd2html/htmlFile.xsl
Labels: Component: Utils
