Repository music-encoding/music-encoding, pull requests merged in 2021-11, with the labels that each got.

#876 remove unused outdated file
  source/css/.qicon
  source/tei_odds.rng
Labels: Status: Ready To Merge

#875 Fix encoding problems in TEI
  source/docs/01-introduction.xml
  source/docs/02-shared.xml
  source/docs/03-metadata.xml
  source/docs/04-cmn.xml
  source/docs/05-mensural.xml
  source/docs/06-neumes.xml
  source/docs/07-tablature.xml
  source/docs/08-lyricsperfdir.xml
  source/docs/09-textencoding.xml
  source/docs/10-analysisharm.xml
  source/docs/11-scholarlyediting.xml
  source/docs/12-facsimilesrecordings.xml
  source/docs/13-linkingdata.xml
  source/docs/14-integration.xml
  source/modules/MEI.analytical.xml
  source/modules/MEI.cmn.xml
  source/modules/MEI.cmnOrnaments.xml
  source/modules/MEI.critapp.xml
  source/modules/MEI.edittrans.xml
  source/modules/MEI.externalsymbols.xml
  source/modules/MEI.frbr.xml
  source/modules/MEI.gestural.xml
  source/modules/MEI.harmony.xml
  source/modules/MEI.header.xml
  source/modules/MEI.lyrics.xml
  source/modules/MEI.mensural.xml
  source/modules/MEI.midi.xml
  source/modules/MEI.msDesc.xml
  source/modules/MEI.neumes.xml
  source/modules/MEI.shared.xml
  source/modules/MEI.text.xml
  source/modules/MEI.usersymbols.xml
  source/modules/MEI.visual.xml
  source/modules/MEI.xml
Labels: Component: Guidelines & Documentation, Component: Core Schema

#874 Improve anyStart schema
  customizations/mei-all_anyStart.xml
Labels: Component: Customizations
