Repository music-encoding/music-encoding, pull requests merged in 2021-04, with the labels that each got.

#781 Update documentation generation
  utils/guidelines_xslt/generateGuidelines.xsl
  utils/guidelines_xslt/odd2html/specs/genericSpecFunctions.xsl
Labels: Component: Utils

#791 add back linkalign docs (fixes #769)
  source/docs/13-linkingdata.xml
  source/examples/linkalign/linkalign-example001.txt
  source/examples/linkalign/linkalign-example002.txt
  source/examples/linkalign/linkalign-example003.txt
  source/examples/linkalign/linkalign-example004.txt
  source/examples/linkalign/linkalign-example005.txt
  source/examples/linkalign/linkalign-example006.txt
  source/examples/linkalign/linkalign-example007.txt
  source/examples/linkalign/linkalign-example008.txt
  source/examples/linkalign/linkalign-example009.txt
  source/examples/linkalign/linkalign-example010.txt
  source/examples/linkalign/linkalign-example011.txt
  source/examples/linkalign/linkalign-example012.txt
  source/examples/linkalign/linkalign-example013.txt
  source/examples/linkalign/linkalign-example014.txt
  source/examples/linkalign/linkalign-example015.txt
  source/examples/linkalign/linkalign-example016.txt
Labels: Component: Guidelines & Documentation

#729 make non-textual elements part of att.enclosingChars
  source/modules/MEI.visual.xml
  source/modules/MEI.xml
Labels: Component: Core Schema
