Repository music-encoding/music-encoding, pull requests merged in 2022-10, with the labels that each got.

#976 Develop style
  source/modules/MEI.analytical.xml
  source/modules/MEI.cmn.xml
  source/modules/MEI.cmnOrnaments.xml
  source/modules/MEI.corpus.xml
  source/modules/MEI.critapp.xml
  source/modules/MEI.drama.xml
  source/modules/MEI.edittrans.xml
  source/modules/MEI.externalsymbols.xml
  source/modules/MEI.facsimile.xml
  source/modules/MEI.figtable.xml
  source/modules/MEI.fingering.xml
  source/modules/MEI.frbr.xml
  source/modules/MEI.genetic.xml
  source/modules/MEI.gestural.xml
  source/modules/MEI.harmony.xml
  source/modules/MEI.header.xml
  source/modules/MEI.lyrics.xml
  source/modules/MEI.mensural.xml
  source/modules/MEI.midi.xml
  source/modules/MEI.msDesc.xml
  source/modules/MEI.namesdates.xml
  source/modules/MEI.neumes.xml
  source/modules/MEI.performance.xml
  source/modules/MEI.ptrref.xml
  source/modules/MEI.shared.xml
  source/modules/MEI.stringtab.xml
  source/modules/MEI.text.xml
  source/modules/MEI.usersymbols.xml
  source/modules/MEI.visual.xml
  source/modules/MEI.xml
  utils/guidelines_xslt/odd2html/specs/elementSpecs.xsl
Labels: Component: Core Schema, Component: Utils

#974 Create att.tuning class
  source/modules/MEI.gestural.xml
  source/modules/MEI.shared.xml
Labels: Component: Core Schema

#981 make stem.vis part of att.extSym and att.visibility
  source/modules/MEI.mensural.xml
Labels: Component: Core Schema, Status: Needs Review

#932 Change macro name of data.OTHERSTAFF
  source/modules/MEI.cmn.xml
  source/modules/MEI.shared.xml
  source/modules/MEI.xml
Labels: Component: Core Schema, Backwards-Compatibility: breaking, Status: Needs Discussion

#998 Make custos part of att.visualOffset.ho
  source/modules/MEI.visual.xml
Labels: Component: Core Schema

#678 More clarity in typography and measurement units
  customizations/mei-basic.xml
  source/modules/MEI.shared.xml
  source/modules/MEI.visual.xml
  source/modules/MEI.xml
Labels: Component: Core Schema, Status: Needs Work, Component: Customizations

#1001 Fix broken build due to failing datatype recognition
  utils/guidelines_xslt/odd2html/specs/genericSpecFunctions.xsl
Labels: Component: Utils

#1009 Adjust paths for pdf guidelines generation
  build.xml
  customizations/mei-basic.xml
  source/modules/MEI.analytical.xml
  source/modules/MEI.cmn.xml
  source/modules/MEI.cmnOrnaments.xml
  source/modules/MEI.corpus.xml
  source/modules/MEI.critapp.xml
  source/modules/MEI.drama.xml
  source/modules/MEI.edittrans.xml
  source/modules/MEI.externalsymbols.xml
  source/modules/MEI.facsimile.xml
  source/modules/MEI.figtable.xml
  source/modules/MEI.fingering.xml
  source/modules/MEI.frbr.xml
  source/modules/MEI.genetic.xml
  source/modules/MEI.gestural.xml
  source/modules/MEI.harmony.xml
  source/modules/MEI.header.xml
  source/modules/MEI.lyrics.xml
  source/modules/MEI.mensural.xml
  source/modules/MEI.midi.xml
  source/modules/MEI.msDesc.xml
  source/modules/MEI.namesdates.xml
  source/modules/MEI.neumes.xml
  source/modules/MEI.performance.xml
  source/modules/MEI.ptrref.xml
  source/modules/MEI.shared.xml
  source/modules/MEI.stringtab.xml
  source/modules/MEI.text.xml
  source/modules/MEI.usersymbols.xml
  source/modules/MEI.visual.xml
  source/modules/MEI.xml
  utils/guidelines_xslt/odd2html/config.xsl
  utils/guidelines_xslt/odd2html/specs/elementSpecs.xsl
  utils/guidelines_xslt/odd2html/specs/genericSpecFunctions.xsl
Labels: Component: Core Schema, Component: Utils, Component: Customizations, Component: Build

#1007 Add persian accidental values
  source/modules/MEI.xml
Labels: Component: Core Schema

#1005 Add `@closed` to att.hairpin.vis
  source/modules/MEI.visual.xml
Labels: Component: Core Schema

#1017 fix missed MEASUREMENTABS
  source/modules/MEI.mensural.xml
Labels: Component: Core Schema

#1003 Add value pedline
  source/modules/MEI.cmn.xml
  source/modules/MEI.visual.xml
  source/modules/MEI.xml
Labels: Component: Core Schema

#806 ODD validation
  source/mei-source.xml
  source/validation/mei-source.sch
Labels: Component: Core Schema, Status: Ready To Merge, Type: Maintenance, Component: Validation

#1014 Update 06-neumes.xml
  source/docs/06-neumes.xml
Labels: Component: Guidelines & Documentation

#1016 add ornamentation accid gestural
  source/modules/MEI.cmnOrnaments.xml
  source/modules/MEI.gestural.xml
Labels: Component: Core Schema

#1004 Develop barlines
  source/modules/MEI.xml
Labels: Component: Core Schema

#1026 Also add data.ACCIDENTAL.persian to data.ACCIDENTAL.WRITTEN
  source/modules/MEI.xml
Labels: Component: Core Schema

#1023 Fix description for pedal style
  source/modules/MEI.cmn.xml
  source/modules/MEI.visual.xml
  source/modules/MEI.xml
Labels: Component: Core Schema

#1013 Use official rng for svg from w3c
  customizations/mei-CMN.xml
  customizations/mei-Mensural.xml
  customizations/mei-Neumes.xml
  customizations/mei-all.xml
  customizations/mei-all_anyStart.xml
  source/svg11.rng
Labels: Status: Needs Work, Component: Customizations

#1021 Add `@opening.vertical` and `@angle.optimize` to att.hairpin.vis
  source/modules/MEI.visual.xml
Labels: Component: Core Schema

#1020 Develop metersig
  source/modules/MEI.cmn.xml
  source/modules/MEI.xml
Labels: Component: Core Schema

#1024 fix model class members display in guidelines
  utils/guidelines_xslt/odd2html/generateWebsite.xsl
  utils/guidelines_xslt/odd2html/specs/genericSpecFunctions.xsl
Labels: Status: Needs Review, Component: Utils

#1018 Add documentation of manifestation singleton
  source/docs/03-metadata.xml
  source/modules/MEI.frbr.xml
  source/modules/MEI.header.xml
Labels: Component: Guidelines & Documentation, Component: Core Schema

#1019 improve neumes nesting
  source/modules/MEI.shared.xml
Labels: Component: Core Schema

#1034 update pdf-guidelines-test from develop branch
  customizations/mei-CMN.xml
  customizations/mei-Mensural.xml
  customizations/mei-Neumes.xml
  customizations/mei-all.xml
  customizations/mei-all_anyStart.xml
  source/docs/03-metadata.xml
  source/docs/06-neumes.xml
  source/mei-source.xml
  source/modules/MEI.cmn.xml
  source/modules/MEI.cmnOrnaments.xml
  source/modules/MEI.frbr.xml
  source/modules/MEI.gestural.xml
  source/modules/MEI.header.xml
  source/modules/MEI.mensural.xml
  source/modules/MEI.shared.xml
  source/modules/MEI.visual.xml
  source/modules/MEI.xml
  source/svg11.rng
  source/validation/mei-source.sch
  utils/guidelines_xslt/odd2html/generateWebsite.xsl
  utils/guidelines_xslt/odd2html/specs/genericSpecFunctions.xsl
Labels: Component: Guidelines & Documentation, Component: Core Schema, Component: Utils, Component: Customizations, Component: Validation

#1033 Update deploy action
  .github/workflows/deploy.yml
Labels: Component: Workflows

#1035 update gh actions
  .github/workflows/deploy.yml
Labels: Component: Workflows

#1008 Develop header footer
  source/docs/02-shared.xml
  source/modules/MEI.shared.xml
  source/modules/MEI.xml
Labels: Component: Guidelines & Documentation, Component: Core Schema

#1038 link moduleFacet to module description
  utils/guidelines_xslt/odd2html/specs/genericSpecFunctions.xsl
Labels: Component: Guidelines & Documentation, Component: Utils

#1032 Remove text.dist and add specific alternatives
  source/modules/MEI.shared.xml
Labels: Component: Core Schema

#1012 Relax schematron on beams
  source/modules/MEI.cmn.xml
Labels: Component: Core Schema

#1027 Clarify remarks for elements based on other standards
  source/modules/MEI.corpus.xml
  source/modules/MEI.critapp.xml
  source/modules/MEI.drama.xml
  source/modules/MEI.edittrans.xml
  source/modules/MEI.facsimile.xml
  source/modules/MEI.figtable.xml
  source/modules/MEI.header.xml
  source/modules/MEI.msDesc.xml
  source/modules/MEI.namesdates.xml
  source/modules/MEI.performance.xml
  source/modules/MEI.ptrref.xml
  source/modules/MEI.shared.xml
  source/modules/MEI.text.xml
Labels: Component: Core Schema

#1025 Fix sources
  source/docs/01-introduction.xml
  source/docs/04-cmn.xml
  source/docs/06-neumes.xml
  source/docs/14-integration.xml
  source/modules/MEI.analytical.xml
  source/modules/MEI.cmn.xml
  source/modules/MEI.cmnOrnaments.xml
  source/modules/MEI.drama.xml
  source/modules/MEI.edittrans.xml
  source/modules/MEI.fingering.xml
  source/modules/MEI.gestural.xml
  source/modules/MEI.harmony.xml
  source/modules/MEI.header.xml
  source/modules/MEI.mensural.xml
  source/modules/MEI.midi.xml
  source/modules/MEI.neumes.xml
  source/modules/MEI.shared.xml
  source/modules/MEI.usersymbols.xml
  source/modules/MEI.visual.xml
  source/modules/MEI.xml
  source/validation/mei-source.sch
Labels: Component: Guidelines & Documentation, Component: Core Schema, Component: Validation

#1037 Fix issue 120 (guidelines repo)
  source/docs/03-metadata.xml
  source/examples/header/header-sample031.txt
Labels: Component: Guidelines & Documentation
