Repository music-encoding/music-encoding, pull requests merged in 2022-04, with the labels that each got.

#921 restrict constraint on clef lines
  source/modules/MEI.shared.xml
Labels: Component: Core Schema, Status: Ready To Merge

#945 update contributors
  source/contributors/curated.contributors.json
  source/mei-source.xml
Labels: Component: Core Schema

#853 Update description on att.numberPlacement
  source/modules/MEI.cmn.xml
Labels: Component: Core Schema, Status: Needs Work

#949 remove remaining remnants
  source/modules/MEI.cmn.xml
  source/modules/MEI.shared.xml
  source/modules/MEI.visual.xml
Labels: Component: Core Schema, Type: Bugfix, Type: Cleanup

#871 Fix copy of web-folder when creating guidelines-html
  build.xml
  source/web/fuse.min.js
Labels: Priority: High, Component: Guidelines & Documentation, Status: Needs Review, Component: Build

#953 fix(guidelines): fix search box positioning and layout
  source/web/css/search.css
  utils/guidelines_xslt/odd2html/htmlFile.xsl
Labels: Component: Guidelines & Documentation, Component: Utils

#939 Update tei.css
  source/css/tei.css
Labels: Status: Ready To Merge
