Repository music-encoding/music-encoding, pull requests merged in 2022-11, with the labels that each got.

#842 Creating att classes for direct children at perfRes(List)
  source/docs/03-metadata.xml
  source/examples/header/header-sample064.txt
  source/modules/MEI.header.xml
Labels: Component: Guidelines & Documentation, Component: Core Schema, Status: Ready To Merge

#1045 Bring facs description in line with TEI
  source/modules/MEI.facsimile.xml
Labels: Component: Core Schema, Status: Ready To Merge

#1053 Fix caption css
  utils/guidelines_xslt/generateGuidelines.xsl
  utils/guidelines_xslt/odd2html/guidelines.xsl
Labels: Component: Utils

#1031 Add border and improve line breaks in classBox
  source/web/css/mei-screen.css
Labels: Component: Guidelines & Documentation
