Repository music-encoding/music-encoding, pull requests merged in 2022-02, with the labels that each got.

#904 respect multiple remarks
  utils/guidelines_xslt/odd2html/specs/genericSpecFunctions.xsl
Labels: Status: Needs Review, Component: Utils, Type: Bugfix

#911 Remodel exhibHist et. al. after provenance
  source/modules/MEI.header.xml
Labels: Component: Core Schema

#910 Use correct typographic symbols in guidelines
  source/docs/01-introduction.xml
  source/docs/03-metadata.xml
  source/docs/04-cmn.xml
  source/docs/05-mensural.xml
  source/docs/07-tablature.xml
  source/modules/MEI.shared.xml
Labels: Component: Guidelines & Documentation, Component: Core Schema

#859 Make layer cue-able
  source/docs/04-cmn.xml
  source/examples/cmn/cmn-cue_layer.txt
  source/examples/cmn/cmn-cue_note.txt
  source/examples/cmn/cmn-ossia_layer.txt
  source/examples/cmn/cmn-ossia_staff.txt
  source/images/modules/cmn/Brahms-flutePart.png
  source/modules/MEI.shared.xml
Labels: Component: Guidelines & Documentation, Component: Core Schema, Type: Feature Request, Component: Images

#905 Fix odd validation on constraint in mensural module
  source/modules/MEI.mensural.xml
Labels: Component: Core Schema

#917 allow app and choice in verse and syl
  source/modules/MEI.lyrics.xml
  source/modules/MEI.shared.xml
Labels: Component: Core Schema

#839 Allow clef changes within fingered tremolos
  source/modules/MEI.cmn.xml
Labels: Component: Core Schema, Status: Ready To Merge

#916 Add description for MEI virtual unit
  source/docs/03-metadata.xml
  source/modules/MEI.shared.xml
  source/modules/MEI.visual.xml
Labels: Component: Guidelines & Documentation, Component: Core Schema, Status: Needs Review
