Repository music-encoding/music-encoding, pull requests merged in 2023-11, with the labels that each got.

#1371 Modify role specific elements
  source/modules/MEI.shared.xml
Labels: Component: Core Schema

#1372 Modify content model of work
  source/modules/MEI.header.xml
Labels: Component: Core Schema

#1373 Modify content model of expression
  source/modules/MEI.frbr.xml
Labels: Component: Core Schema

#1368 Add profileDescPart model class
  source/modules/MEI.shared.xml
Labels: Component: Core Schema

#1366 Add biblFull element
  source/modules/MEI.shared.xml
Labels: Component: Core Schema

#1386 schema: replace version 5.0 with dev
  customizations/mei-CMN.xml
  customizations/mei-Mensural.xml
  customizations/mei-Neumes.xml
  customizations/mei-all.xml
  customizations/mei-all_anyStart.xml
  customizations/mei-basic.xml
  source/docs/01-introduction.xml
  source/examples/neumes/neumes-sample169.txt
  source/examples/shared/shared-sample0000.txt
  source/examples/shared/shared-sample0001.txt
  source/examples/shared/shared-sample0002.txt
  source/examples/shared/shared-sample0003.txt
  source/examples/svg/svg-example.xml
  source/examples/verovio/04-score-redefinition.mei
  source/examples/verovio/accid-03.mei
  source/examples/verovio/alteration.mei
  source/examples/verovio/ars_antiqua.mei
  source/examples/verovio/augmentation.mei
  source/examples/verovio/editorial_example.mei
  source/examples/verovio/imperfection.mei
  source/examples/verovio/implicit-mensuration.mei
  source/examples/verovio/mensuration_changes.mei
  source/examples/verovio/motet_fauvel_fol22r_triplum.mei
  source/examples/verovio/notes_rests.mei
  source/examples/verovio/octave-shift-01.mei
  source/examples/verovio/partial-imp-01-propinquam.mei
  source/examples/verovio/partial-imp-02-bilateral.mei
  source/examples/verovio/partial-imp-03-remotam.mei
  source/examples/verovio/partial-imp-04-remotam.mei
  source/examples/verovio/tempo-01.mei
  source/mei-source.xml
  source/modules/MEI.shared.xml
Labels: Component: Guidelines & Documentation, Component: Core Schema, Component: Customizations

#1325 schema: re-enable staff positioning of rests in MEI Basic
  customizations/mei-basic.xml
Labels: Component: Customizations
