Repository music-encoding/music-encoding, pull requests merged in 2023-05, with the labels that each got.

#1110 Improve build instructions and reorganize README
  BUILD_COMMANDLINE.md
  BUILD_OXYGEN.md
  CLONING.md
  CONTRIBUTING.md
  README.md
  build.xml
Labels: Status: Needs Review, Component: Build

#1121 Fix docker-mei ant command in deploy workflow
  .github/workflows/deploy.yml
Labels: Component: Workflows

#1123 Fix: git sha and ref
  build.xml
Labels: Component: Build

#1137 build.xml: add target for building customization specs
  build.xml
Labels: Component: Build

#1136 feat(gh-actions): upload artifacts on action run
  .github/workflows/deploy.yml
Labels: Component: Workflows

#1127 fix(source): replace umlaut in file name
  source/assets/images/modules/edittrans/schuetz_sopranoclef.png
  source/docs/11-scholarlyediting.xml
  source/unusedImages.txt
  source/usedImages.txt
Labels: Component: Guidelines & Documentation

#1106 fix(guidelines): fix bibliographic references in neumes chapter
  source/docs/06-neumes.xml
Labels: Component: Guidelines & Documentation, Status: Ready To Merge

#1124 Fixed: Clarify use of GG clef shape
  source/modules/MEI.xml
Labels: Component: Core Schema

#1139 Fix deployment action breaking
  .github/workflows/deploy.yml
Labels: Priority: Critical, Component: Tools, Component: Workflows, Type: Bugfix

#933 adapt instrDef to staffDef
  source/modules/MEI.midi.xml
Labels: Component: Core Schema, Backwards-Compatibility: breaking, Status: Needs Review

#1132 remove combining reverse solidus example
  source/docs/10-analysisharm.xml
  source/examples/harmony/harmony-sample271.txt
Labels: Component: Guidelines & Documentation

#1147 fix(neumes): fix incorrect attribute classes in neumes customization
  customizations/mei-Neumes.xml
Labels: Component: Customizations

#1130 spread out constraints to affected elements
  source/modules/MEI.header.xml
  source/modules/MEI.msDesc.xml
Labels: Component: Core Schema

#1141 Develop basic cleanup
  customizations/mei-basic.xml
Labels: Component: MEI Basic, Component: Customizations

#1149 rename attribute reference in altId remark
  source/modules/MEI.header.xml
Labels: Component: Core Schema, Status: Ready To Merge, Type: Bugfix

#1150 Add "fences" as a notehead modifier
  source/modules/MEI.xml
Labels: Component: Core Schema, Priority: Medium, Status: Needs Review, Type: Bugfix

#1140 feat(performance): adding extData
  source/docs/12-facsimilesrecordings.xml
  source/examples/performances/performances-sample336.txt
  source/modules/MEI.performance.xml
  source/modules/MEI.shared.xml
Labels: Component: Guidelines & Documentation, Component: Core Schema

#1151 allow tstamp2.ges and tstamp2.real on metaMark
  source/modules/MEI.gestural.xml
Labels: Component: Core Schema, Type: Regression, Status: Needs Review, Type: Bugfix

#1142 Fixed: Add glyph.auth and glyph.uri to rend
  source/docs/09-textencoding.xml
  source/examples/text/text-sample375.txt
  source/modules/MEI.externalsymbols.xml
  source/modules/MEI.shared.xml
Labels: Priority: High, Component: Guidelines & Documentation, Component: Core Schema, Type: Feature Request

#1154 fix data.PERCENT
  source/modules/MEI.xml
Labels: Component: Core Schema

#1155 Fixed: instrDef was misspelled
  customizations/mei-basic.xml
Labels: Priority: High, Type: Bugfix, Component: Customizations

#1148 Cleanup Verovio examples
  source/examples/verovio/accid-03.mei
  source/examples/verovio/alteration.mei
  source/examples/verovio/ars_antiqua.mei
  source/examples/verovio/augmentation.mei
  source/examples/verovio/imperfection.mei
  source/examples/verovio/implicit-mensuration.mei
  source/examples/verovio/mensuration_changes.mei
  source/examples/verovio/motet_fauvel_fol22r_triplum.mei
  source/examples/verovio/notes_rests.mei
  source/examples/verovio/octave-shift-01.mei
  source/examples/verovio/partial-imp-01-propinquam.mei
  source/examples/verovio/partial-imp-02-bilateral.mei
  source/examples/verovio/partial-imp-03-remotam.mei
  source/examples/verovio/partial-imp-04-remotam.mei
  source/examples/verovio/tempo-01.mei
Labels: Component: Guidelines & Documentation

#1022 A expanMark element for encoding coda, segno and similar marks
  source/modules/MEI.analytical.xml
  source/modules/MEI.cmn.xml
  source/modules/MEI.gestural.xml
  source/modules/MEI.shared.xml
  source/modules/MEI.visual.xml
Labels: Component: Core Schema

#1161 Fixed: Use value of "schematron" for constraintSpec
  customizations/mei-CMN.xml
  customizations/mei-Mensural.xml
  customizations/mei-Neumes.xml
  customizations/mei-all.xml
  customizations/mei-all_anyStart.xml
  customizations/mei-basic.xml
  source/modules/MEI.cmn.xml
  source/modules/MEI.cmnOrnaments.xml
  source/modules/MEI.drama.xml
  source/modules/MEI.edittrans.xml
  source/modules/MEI.externalsymbols.xml
  source/modules/MEI.facsimile.xml
  source/modules/MEI.figtable.xml
  source/modules/MEI.fingering.xml
  source/modules/MEI.gestural.xml
  source/modules/MEI.harmony.xml
  source/modules/MEI.header.xml
  source/modules/MEI.mensural.xml
  source/modules/MEI.midi.xml
  source/modules/MEI.msDesc.xml
  source/modules/MEI.performance.xml
  source/modules/MEI.shared.xml
  source/modules/MEI.text.xml
  source/modules/MEI.usersymbols.xml
  source/modules/MEI.visual.xml
  source/modules/MEI.xml
Labels: Component: Core Schema, Priority: Medium, Component: Tools, Component: Customizations

#1179 fix(source): fix typos
  source/docs/10-analysisharm.xml
  source/examples/verovio/tempo-01.mei
Labels: Component: Guidelines & Documentation

#1178 fix(build): remove xml declaration from example mei files
  source/examples/verovio/accid-03.mei
  source/examples/verovio/alteration.mei
  source/examples/verovio/ars_antiqua.mei
  source/examples/verovio/augmentation.mei
  source/examples/verovio/imperfection.mei
  source/examples/verovio/implicit-mensuration.mei
  source/examples/verovio/mensuration_changes.mei
  source/examples/verovio/motet_fauvel_fol22r_triplum.mei
  source/examples/verovio/notes_rests.mei
  source/examples/verovio/octave-shift-01.mei
  source/examples/verovio/partial-imp-01-propinquam.mei
  source/examples/verovio/partial-imp-02-bilateral.mei
  source/examples/verovio/partial-imp-03-remotam.mei
  source/examples/verovio/partial-imp-04-remotam.mei
  source/examples/verovio/tempo-01.mei
Labels: Component: Guidelines & Documentation

#1152 fix(build): include oxygen-basic-utilites in lib
  build.xml
Labels: Component: Build

#1165 feat(build): describe ant targets in BUILD_COMMANDLINE
  BUILD_COMMANDLINE.md
  build.xml
Labels: Status: Needs Review, Component: Build

#1181 Harmonize gestural data types
  customizations/mei-basic.xml
  source/modules/MEI.gestural.xml
  source/modules/MEI.xml
Labels: Component: Core Schema, Backwards-Compatibility: breaking, Component: Customizations
