Repository music-encoding/music-encoding, pull requests merged in 2023-06, with the labels that each got.

#1172 Allow <availability> within <imprint>
  source/modules/MEI.header.xml
Labels: Component: Core Schema, Status: Needs Review

#1192 Update BUILD_OXYGEN.md
  BUILD_OXYGEN.md
Labels: Component: Guidelines & Documentation

#1170 Fixed: Key signature changes
  source/docs/04-cmn.xml
  source/examples/cmn/cmn-sample095.txt
  source/examples/cmn/cmn-sample097.txt
  source/examples/cmnOrnaments/cmnOrnaments-sample198.txt
  source/examples/lyricsDesc/lyricsDesc-sample283.txt
  source/examples/midiGuidelines/midiGuidelines-sample286.txt
  source/examples/midiGuidelines/midiGuidelines-sample287.txt
  source/examples/midiGuidelines/midiGuidelines-sample288.txt
  source/examples/midiGuidelines/midiGuidelines-sample289.txt
  source/examples/verovio/04-score-redefinition.mei
  source/modules/MEI.shared.xml
  source/modules/MEI.visual.xml
  source/modules/MEI.xml
Labels: Priority: High, Component: Guidelines & Documentation, Component: Core Schema, Status: Needs Review

#1205 fix(gh-actions): do not run deploy steps on forks
  .github/workflows/deploy.yml
Labels: Component: Workflows

#1208 Add `ending` to MEI-Basic
  customizations/mei-basic.xml
Labels: Component: MEI Basic, Component: Customizations

#1207 Adjust MEI- Basic customization to use att.duration.log for rest
  customizations/mei-basic.xml
Labels: Component: MEI Basic, Component: Customizations

#1188 Remove "italic" and "oblique" values from data.TEXTRENDITIONLIST
  source/modules/MEI.xml
Labels: Component: Core Schema

#1196 Improve init target
  build.xml
Labels: Component: Build

#1193 Update BUILD_COMMANDLINE.md
  BUILD_COMMANDLINE.md
Labels: Status: Needs Review

#1200 build.xml: introduce property `verbose`
  build.xml
Labels: Component: Build

#1215 add comparison xslt
  utils/compare_versions/README.md
  utils/compare_versions/comparison.xsl
  utils/compare_versions/resources/css/main.css
  utils/compare_versions/resources/js/d3.min.js
  utils/compare_versions/resources/js/main.js
Labels: Component: Utils

#1214 Revert "Remove "italic" and "oblique" values from data.TEXTRENDITIONLIST"
  source/modules/MEI.xml
Labels: Component: Core Schema

#1184 Initial script for generating images using a python script instead of…
  BUILD_COMMANDLINE.md
  build.xml
  utils/examples/generate-examples.py
Labels: Status: Needs Review, Component: Utils, Component: Build

#1091 Introduce docu, Gl 3.7: plateNum
  source/docs/03-metadata.xml
  source/examples/header/header-sample095.txt
Labels: Component: Guidelines & Documentation

#1089 Introduce docu, Gl 3.7: condition, colophon
  source/docs/03-metadata.xml
Labels: Component: Guidelines & Documentation

#1093 guidelines: update list of authors in Chapter 3
  source/docs/03-metadata.xml
Labels: Component: Guidelines & Documentation

#1233 customizations: allow `breaksec` in MEI-Basic
  customizations/mei-basic.xml
Labels: Component: Customizations

#1226 guidelines: fix caption for curve shape
  source/docs/02-shared.xml
Labels: Component: Guidelines & Documentation, Priority: Medium, Status: Needs Review, Type: Bugfix

#1191 guidelines: fix Chapter 5
  source/assets/images/modules/mensural/ex_plicae.png
  source/docs/05-mensural.xml
  source/examples/mensural/mensural-sample153.txt
  source/examples/mensural/mensural-sample164.txt
  source/examples/mensural/mensural-sample165.txt
  source/examples/verovio/alteration.mei
  source/examples/verovio/ars_antiqua.mei
  source/examples/verovio/augmentation.mei
  source/examples/verovio/imperfection.mei
  source/examples/verovio/implicit-mensuration.mei
  source/examples/verovio/partial-imp-01-propinquam.mei
  source/examples/verovio/partial-imp-02-bilateral.mei
  source/examples/verovio/partial-imp-03-remotam.mei
  source/examples/verovio/partial-imp-04-remotam.mei
Labels: Component: Guidelines & Documentation, Status: Needs Review

#1220 docs: adjust version numbers in BUILD_COMMANDLINE readme
  BUILD_COMMANDLINE.md
Labels: Status: Needs Review, Type: Bugfix

#1221 build: check for prince
  build.xml
Labels: Status: Needs Review, Type: Bugfix, Component: Build

#1232 guidelines: fix style typo in chapter 1
  source/docs/01-introduction.xml
Labels: Component: Guidelines & Documentation

#1236 Revert "build: check for prince"
  build.xml
Labels: Component: Build

#1094 guidelines: introduce docu, Gl 3.7: addDesc
  source/docs/03-metadata.xml
  source/examples/header/header-sample089.txt
  source/examples/header/header-sample090.txt
  source/examples/header/header-sample091.txt
  source/examples/header/header-sample092.txt
Labels: Component: Guidelines & Documentation

#1216 schema: align description with guidelines
  source/modules/MEI.xml
Labels: Component: Core Schema

#1225 guidelines: clear up description of line rendition
  source/docs/02-shared.xml
Labels: Component: Guidelines & Documentation

#1223 gh-actions: fix hard-coded PDF name in deploy action
  .github/workflows/deploy.yml
Labels: Status: Needs Review, Component: Workflows

#1237 Fix/if prince available
  BUILD_COMMANDLINE.md
  build.xml
  customizations/mei-basic.xml
  source/assets/images/modules/mensural/ex_plicae.png
  source/docs/01-introduction.xml
  source/docs/02-shared.xml
  source/docs/05-mensural.xml
  source/examples/mensural/mensural-sample153.txt
  source/examples/mensural/mensural-sample164.txt
  source/examples/mensural/mensural-sample165.txt
  source/examples/verovio/alteration.mei
  source/examples/verovio/ars_antiqua.mei
  source/examples/verovio/augmentation.mei
  source/examples/verovio/imperfection.mei
  source/examples/verovio/implicit-mensuration.mei
  source/examples/verovio/partial-imp-01-propinquam.mei
  source/examples/verovio/partial-imp-02-bilateral.mei
  source/examples/verovio/partial-imp-03-remotam.mei
  source/examples/verovio/partial-imp-04-remotam.mei
  source/modules/MEI.xml
  utils/compare_versions/README.md
  utils/compare_versions/comparison.xsl
  utils/compare_versions/resources/css/main.css
  utils/compare_versions/resources/js/d3.min.js
  utils/compare_versions/resources/js/main.js
  utils/examples/generate-examples.py
Labels: Component: Guidelines & Documentation, Component: Core Schema, Component: Utils, Component: Customizations, Component: Build

#1235 customizations: add `<symbol>` to MEI Basic
  customizations/mei-basic.xml
Labels: Priority: High, Component: MEI Basic, Component: Customizations

#1242 customizations: adjustment to MEI Basic
  customizations/mei-basic.xml
Labels: Component: MEI Basic, Component: Customizations

#1243 customizations: adjustment to MEI Basic (2)
  customizations/mei-basic.xml
Labels: Component: Customizations

#1244 customizations: fix `chord@breaksec` missing in MEI Basic
  customizations/mei-basic.xml
Labels: Priority: High, Component: MEI Basic, Component: Customizations

#1229 schema: extracting some missed gloss
  source/modules/MEI.cmn.xml
  source/modules/MEI.critapp.xml
  source/modules/MEI.fingering.xml
  source/modules/MEI.genetic.xml
  source/modules/MEI.header.xml
  source/modules/MEI.namesdates.xml
  source/modules/MEI.neumes.xml
  source/modules/MEI.text.xml
  source/modules/MEI.visual.xml
Labels: Component: Core Schema, Status: Needs Review

#1212 schema: fix visibility of mRest and multiRest
  source/modules/MEI.visual.xml
Labels: Component: Core Schema, Status: Needs Review

#1238 utils: remove unnecessary type attribute on script
  utils/compare_versions/comparison.xsl
  utils/guidelines_xslt/odd2html/htmlFile.xsl
Labels: Status: Needs Review, Component: Utils

#1246 schema: create a `att.runningtext` attribute class
  source/modules/MEI.shared.xml
Labels: Component: Core Schema

#1247 schema: rename att.runningtext to att.formework
  source/modules/MEI.shared.xml
Labels: Component: Core Schema
