Repository music-encoding/music-encoding, pull requests merged in 2023-08, with the labels that each got.

#1295 schema: fix schematron phys desc ancestors
  source/modules/MEI.header.xml
  source/modules/MEI.msDesc.xml
Labels: Component: Core Schema, Status: Needs Review

#1298 guidelines: fix typos in chapter 1
  source/docs/01-introduction.xml
Labels: Component: Guidelines & Documentation

#1304 guidelines: fix markup of attribute values
  source/docs/03-metadata.xml
Labels: Component: Guidelines & Documentation

#1305 guidelines: correction of correction
  source/docs/03-metadata.xml
Labels: Priority: High, Component: Guidelines & Documentation

#1301 guidelines: fix syntax errors
  source/contributors/curated.contributors.json
  source/docs/01-introduction.xml
  source/docs/05-mensural.xml
  source/docs/08-lyricsperfdir.xml
  source/docs/09-textencoding.xml
Labels: Component: Guidelines & Documentation

#1303 customizations: fix start elements in anystart
  customizations/mei-all_anyStart.xml
Labels: Component: Customizations

#1306 style: add css rule for span.val in PDF guidelines
  source/assets/css/print/mei.css
Labels: Component: Style

#1307 guidelines: add attribute changes to "about version" section
  source/docs/01-introduction.xml
Labels: Component: Guidelines & Documentation

#1309 customizations: fix missing `@n` in verse in MEI Basic
  customizations/mei-basic.xml
Labels: Component: Customizations

#1300 schema: reduce version number
  customizations/mei-all_anyStart.xml
  customizations/mei-basic.xml
  source/examples/neumes/neumes-sample169.txt
  source/examples/verovio/04-score-redefinition.mei
  source/examples/verovio/accid-03.mei
  source/examples/verovio/alteration.mei
  source/examples/verovio/ars_antiqua.mei
  source/examples/verovio/augmentation.mei
  source/examples/verovio/imperfection.mei
  source/examples/verovio/implicit-mensuration.mei
  source/examples/verovio/mensuration_changes.mei
  source/examples/verovio/motet_fauvel_fol22r_triplum.mei
  source/examples/verovio/notes_rests.mei
  source/examples/verovio/octave-shift-01.mei
  source/examples/verovio/partial-imp-01-propinquam.mei
  source/examples/verovio/partial-imp-02-bilateral.mei
  source/examples/verovio/partial-imp-03-remotam.mei
  source/examples/verovio/partial-imp-04-remotam.mei
  source/examples/verovio/tempo-01.mei
  source/mei-source.xml
  source/modules/MEI.shared.xml
Labels: Component: Guidelines & Documentation, Component: Core Schema, Component: Customizations

#1311 Editorial pass on 5.0 release notes
  source/docs/01-introduction.xml
Labels: Component: Guidelines & Documentation

#1308 guidelines: add small section on enclose attribute
  source/assets/images/modules/edittrans/editorial_example.png
  source/docs/11-scholarlyediting.xml
  source/examples/editTrans/editorial01.txt
  source/examples/editTrans/editorial02.txt
  source/examples/verovio/editorial_example.mei
Labels: Component: Guidelines & Documentation

#1323 Fix malformed XML
  source/docs/01-introduction.xml
Labels: Component: Guidelines & Documentation

#1320 Fix: #1314 mei basic unclear status of attribute classes
  customizations/mei-basic.xml
Labels: Status: Needs Review, Type: Bugfix, Component: Customizations

#1313 Fix MEI Basic
  customizations/mei-basic.xml
Labels: Priority: Critical, Component: MEI Basic, Type: Bugfix, Component: Customizations

#1293 schema: unify customization namespaces
  customizations/mei-CMN.xml
  customizations/mei-Mensural.xml
  customizations/mei-Neumes.xml
  customizations/mei-all.xml
  customizations/mei-all_anyStart.xml
  customizations/mei-basic.xml
Labels: Component: Customizations

#1319 customizations: implement customization specific version numbers with suffix
  customizations/mei-CMN.xml
  customizations/mei-Mensural.xml
  customizations/mei-Neumes.xml
  customizations/mei-all.xml
  customizations/mei-all_anyStart.xml
  customizations/mei-basic.xml
  source/examples/neumes/neumes-sample169.txt
  source/examples/verovio/04-score-redefinition.mei
  source/examples/verovio/accid-03.mei
  source/examples/verovio/alteration.mei
  source/examples/verovio/ars_antiqua.mei
  source/examples/verovio/augmentation.mei
  source/examples/verovio/imperfection.mei
  source/examples/verovio/implicit-mensuration.mei
  source/examples/verovio/mensuration_changes.mei
  source/examples/verovio/motet_fauvel_fol22r_triplum.mei
  source/examples/verovio/notes_rests.mei
  source/examples/verovio/octave-shift-01.mei
  source/examples/verovio/partial-imp-01-propinquam.mei
  source/examples/verovio/partial-imp-02-bilateral.mei
  source/examples/verovio/partial-imp-03-remotam.mei
  source/examples/verovio/partial-imp-04-remotam.mei
  source/examples/verovio/tempo-01.mei
  source/modules/MEI.shared.xml
Labels: Component: Guidelines & Documentation, Component: Core Schema, Status: Needs Review, Component: Customizations

#1326 schema: fix schema-references and edit-section processing-instructions errors
  source/examples/svg/svg-example.xml
  source/examples/svg/svg-moduleRef.xml
  source/examples/verovio/editorial_example.mei
Labels: Component: Guidelines & Documentation

#1327 utils: process following-sibling after edit-start processing-instruction
  utils/guidelines_xslt/odd2html/guidelines.xsl
Labels: Component: Utils

#1321 gh-actions: improve gh action for tag pushes to stable branch
  .github/workflows/deploy.yml
Labels: Status: Needs Review, Component: Workflows

#1328 guidelines: fix shared example
  source/docs/02-shared.xml
  source/examples/shared/shared-sample0000.txt
  source/examples/shared/shared-sample0001.txt
  source/examples/shared/shared-sample0002.txt
  source/examples/shared/shared-sample0003.txt
Labels: Component: Guidelines & Documentation
