Repository music-encoding/music-encoding, pull requests merged in 2023-07, with the labels that each got.

#1241 gh-actions: fix hard-coded PDF name in deploy action, part 2
  .github/workflows/deploy.yml
Labels: Status: Needs Review, Component: Workflows

#1245 schema: update license version and add publicationStmt to customizations
  customizations/mei-CMN.xml
  customizations/mei-Mensural.xml
  customizations/mei-Neumes.xml
  customizations/mei-all.xml
  customizations/mei-all_anyStart.xml
  customizations/mei-basic.xml
Labels: Status: Needs Review, Component: Customizations

#1230 guidelines: remove reference to ineume and uneume in chapter 6
  source/docs/06-neumes.xml
Labels: Component: Guidelines & Documentation

#1248 schema: allow repeated pgHead and pgFoot in scoreDef
  source/modules/MEI.shared.xml
Labels: Component: Core Schema, Priority: Critical, Status: Needs Review

#1239 build: only run prince if command found
  build.xml
Labels: Status: Needs Review, Component: Build

#1209 build: improve classpath handling
  BUILD_COMMANDLINE.md
  build.xml
Labels: Priority: Critical, Status: Needs Review, Component: Build

#1253 build: make init-mei-classpath depend on init target
  build.xml
Labels: Component: Build

#1157 schema: resolve att def duplications
  source/docs/06-neumes.xml
  source/modules/MEI.analytical.xml
  source/modules/MEI.cmn.xml
  source/modules/MEI.figtable.xml
  source/modules/MEI.gestural.xml
  source/modules/MEI.header.xml
  source/modules/MEI.msDesc.xml
  source/modules/MEI.neumes.xml
  source/modules/MEI.shared.xml
  source/modules/MEI.visual.xml
Labels: Component: Guidelines & Documentation, Component: Core Schema, Status: Needs Decision, Type: Maintenance, Status: Needs Testing

#1198 guidelines: move changes from ig-metadata branch into develop for MEI v5.0
  source/docs/03-metadata.xml
  source/examples/header/header-sample081.txt
  source/examples/header/header-sample082.txt
  source/examples/header/header-sample083.txt
  source/examples/header/header-sample084.txt
  source/examples/header/header-sample085.txt
  source/examples/header/header-sample086.txt
  source/examples/header/header-sample087.txt
  source/examples/header/header-sample088.txt
  source/examples/header/header-sample089.txt
  source/examples/header/header-sample090.txt
  source/examples/header/header-sample091.txt
  source/examples/header/header-sample092.txt
  source/examples/header/header-sample094.txt
  source/examples/header/header-sample095.txt
  source/examples/header/header-sample096.txt
Labels: Component: Guidelines & Documentation, Status: Needs Work

#1218 guidelines: fix and unify examples
  source/examples/verovio/04-score-redefinition.mei
  source/examples/verovio/accid-03.mei
  source/examples/verovio/alteration.mei
  source/examples/verovio/ars_antiqua.mei
  source/examples/verovio/augmentation.mei
  source/examples/verovio/imperfection.mei
  source/examples/verovio/implicit-mensuration.mei
  source/examples/verovio/mensuration_changes.mei
  source/examples/verovio/motet_fauvel_fol22r_triplum.mei
  source/examples/verovio/notes_rests.mei
  source/examples/verovio/octave-shift-01.mei
  source/examples/verovio/partial-imp-01-propinquam.mei
  source/examples/verovio/partial-imp-02-bilateral.mei
  source/examples/verovio/partial-imp-03-remotam.mei
  source/examples/verovio/partial-imp-04-remotam.mei
  source/examples/verovio/tempo-01.mei
Labels: Component: Guidelines & Documentation, Status: Needs Review

#1258 guidelines: replace markdown syntax in chapter 6
  source/docs/06-neumes.xml
Labels: Component: Guidelines & Documentation

#1261 schema: remove duplicated attributes to ensure schema validity
  customizations/mei-basic.xml
  source/modules/MEI.shared.xml
Labels: Component: Core Schema, Priority: Critical, Status: Needs Review, Type: Bugfix, Component: Customizations

#1266 utils: fix display of facet tab contents in guidelines html
  utils/guidelines_xslt/odd2html/htmlFile.xsl
Labels: Priority: Critical, Component: Utils

#1252 guidelines: remove references to removed literature from chapter 6
  source/docs/06-neumes.xml
Labels: Component: Guidelines & Documentation

#1264 build: avoid multiple runs of initial targets and improve logging
  build.xml
Labels: Component: Build

#1274 customizations: do not delete att.curveRend in MEI Basic
  customizations/mei-basic.xml
Labels: Component: Customizations

#1275 guidelines: add `@n` to layer in examples
  source/examples/verovio/implicit-mensuration.mei
Labels: Component: Guidelines & Documentation

#1277 docs: fixing a small typo in name
  source/docs/01-introduction.xml
  source/mei-source.xml
Labels: Component: Guidelines & Documentation, Component: Core Schema

#1268 schema: add missing values for double accidentals
  source/modules/MEI.xml
Labels: Component: Core Schema, Status: Needs Review

#1281 customizations: adjust att.harm.vis in MEI Basic
  customizations/mei-basic.xml
Labels: Component: MEI Basic, Component: Customizations

#1278 docs(build): update and sync target descriptions
  BUILD_COMMANDLINE.md
  build.xml
Labels: Component: Guidelines & Documentation, Component: Build

#1279 schema: remove curveRend in favor of lineRend.base
  customizations/mei-basic.xml
  source/docs/02-shared.xml
  source/modules/MEI.cmn.xml
  source/modules/MEI.shared.xml
  source/modules/MEI.visual.xml
Labels: Component: Guidelines & Documentation, Component: Core Schema, Component: Customizations

#1287 schema: fix double entries in att.neumeTypes
  source/modules/MEI.neumes.xml
Labels: Component: Core Schema

#1288 schema: add support to encode the level where a proportion is applied
  source/docs/05-mensural.xml
  source/modules/MEI.shared.xml
Labels: Component: Guidelines & Documentation, Component: Core Schema

#1284 guidelines: update introduction chapter
  source/docs/01-introduction.xml
  source/docs/14-integration.xml
Labels: Component: Guidelines & Documentation

#1285 schema: align att.arpeg.vis with other line-like elements
  source/modules/MEI.visual.xml
Labels: Component: Core Schema, Status: Needs Review

#1292 guidelines: update GitHub user name
  source/contributors/curated.contributors.json
  source/docs/01-introduction.xml
  source/docs/02-shared.xml
  source/docs/03-metadata.xml
  source/docs/04-cmn.xml
  source/docs/05-mensural.xml
  source/docs/06-neumes.xml
  source/docs/07-tablature.xml
  source/docs/08-lyricsperfdir.xml
  source/docs/09-textencoding.xml
  source/docs/10-analysisharm.xml
  source/docs/11-scholarlyediting.xml
  source/docs/12-facsimilesrecordings.xml
  source/docs/13-linkingdata.xml
  source/docs/14-integration.xml
Labels: Component: Guidelines & Documentation

#1296 guidelines: add missing contributors (2)
  source/contributors/curated.contributors.json
  utils/guidelines_xslt/odd2html/functions.xsl
Labels: Component: Utils
