Repository music-encoding/music-encoding, pull requests merged in 2023-01, with the labels that each got.

#1064 Fixing a bunch of small typos
  source/docs/01-introduction.xml
  source/docs/02-shared.xml
  source/docs/03-metadata.xml
  source/docs/04-cmn.xml
  source/docs/05-mensural.xml
  source/docs/08-lyricsperfdir.xml
  source/docs/09-textencoding.xml
  source/docs/10-analysisharm.xml
  source/docs/11-scholarlyediting.xml
  source/docs/14-integration.xml
Labels: Component: Guidelines & Documentation

#990 Restructure guidelines chapter 3.7 for elaboration
  source/docs/03-metadata.xml
  source/examples/header/header-sample080.txt
Labels: Component: Guidelines & Documentation

#1057 Update ant build to saxon 11
  .github/workflows/deploy.yml
  README.md
  build.xml
Labels: Component: Workflows, Component: Build

#1058 Update documentation on lyrics
  source/docs/08-lyricsperfdir.xml
  source/examples/lyricsDesc/lyricsDesc-sample284.txt
  source/examples/lyricsDesc/lyricsDesc-sample285.txt
  source/examples/lyricsDesc/vagabond.txt
Labels: Component: Guidelines & Documentation

#1047 Add glossaries to attribute definitions
  source/modules/MEI.analytical.xml
  source/modules/MEI.cmn.xml
  source/modules/MEI.cmnOrnaments.xml
  source/modules/MEI.edittrans.xml
  source/modules/MEI.gestural.xml
  source/modules/MEI.harmony.xml
  source/modules/MEI.midi.xml
  source/modules/MEI.neumes.xml
  source/modules/MEI.shared.xml
  source/modules/MEI.visual.xml
Labels: Component: Core Schema, Status: Needs Review
