Repository music-encoding/music-encoding, pull requests merged in 2024-01, with the labels that each got.

#1403 docs: remove superfluous quotes on values
  source/modules/MEI.shared.xml
Labels: Component: Core Schema

#1404 guidelines: enhance documentation of linking attributes
  source/docs/10-analysisharm.xml
  source/docs/13-linkingdata.xml
  source/examples/linkalign/linkalign-example017.txt
  source/examples/linkalign/linkalign-example018.txt
  source/examples/linkalign/linkalign-example019.txt
  source/examples/linkalign/linkalign-example020.txt
  source/examples/linkalign/linkalign-example021.txt
  source/examples/linkalign/linkalign-example022.txt
  source/examples/linkalign/linkalign-example023.txt
  source/examples/verovio/att-corresp.mei
Labels: Component: Guidelines & Documentation

#1405 docs: add remark about neume customization to neume element
  source/modules/MEI.neumes.xml
Labels: Component: Core Schema

#1406 utils: improve logging output for build-guidelines-html step
  utils/guidelines_xslt/odd2html.xsl
  utils/guidelines_xslt/odd2html/functions.xsl
  utils/guidelines_xslt/odd2html/generateWebsite.xsl
  utils/guidelines_xslt/odd2html/prepareLiveExamples.xsl
  utils/guidelines_xslt/odd2html/specs/attClassSpecs.xsl
  utils/guidelines_xslt/odd2html/specs/dataTypeSpecs.xsl
  utils/guidelines_xslt/odd2html/specs/elementSpecs.xsl
  utils/guidelines_xslt/odd2html/specs/macroGroupSpecs.xsl
  utils/guidelines_xslt/odd2html/specs/modelClassSpecs.xsl
Labels: Component: Utils

#1399 docs: update remarks for score element
  source/modules/MEI.shared.xml
Labels: Component: Guidelines & Documentation

#1289 schema: remove doubled namespace declaration
  source/mei-source.xml
  source/modules/MEI.analytical.xml
  source/modules/MEI.cmn.xml
  source/modules/MEI.cmnOrnaments.xml
  source/modules/MEI.corpus.xml
  source/modules/MEI.critapp.xml
  source/modules/MEI.drama.xml
  source/modules/MEI.edittrans.xml
  source/modules/MEI.externalsymbols.xml
  source/modules/MEI.facsimile.xml
  source/modules/MEI.figtable.xml
  source/modules/MEI.fingering.xml
  source/modules/MEI.frbr.xml
  source/modules/MEI.genetic.xml
  source/modules/MEI.gestural.xml
  source/modules/MEI.harmony.xml
  source/modules/MEI.header.xml
  source/modules/MEI.lyrics.xml
  source/modules/MEI.mensural.xml
  source/modules/MEI.midi.xml
  source/modules/MEI.msDesc.xml
  source/modules/MEI.namesdates.xml
  source/modules/MEI.neumes.xml
  source/modules/MEI.performance.xml
  source/modules/MEI.ptrref.xml
  source/modules/MEI.shared.xml
  source/modules/MEI.stringtab.xml
  source/modules/MEI.text.xml
  source/modules/MEI.usersymbols.xml
  source/modules/MEI.visual.xml
  source/modules/MEI.xml
Labels: Component: Core Schema

#1415 utils: fix wording for datatype list values
  utils/guidelines_xslt/odd2html/specs/dataTypeSpecs.xsl
  utils/guidelines_xslt/odd2html/specs/genericSpecFunctions.xsl
Labels: Component: Utils

#1414 guidelines: fix the end tag of edit section in tempo example file
  source/examples/verovio/tempo-01.mei
Labels: Component: Guidelines & Documentation

#1409 guidelines: add missing captions (heads) to the guidelines chapter on Mensural Notation
  source/docs/05-mensural.xml
Labels: Component: Guidelines & Documentation

#1391 validation: make mei-customizations.sch check any customization
  source/validation/mei-customizations.sch
Labels: Component: Validation

#1408 schema: update schematron rule for mixed beams
  source/modules/MEI.cmn.xml
Labels: Component: Core Schema

#1393 schema: allow additive `@dur` on <halfmRpt>
  source/modules/MEI.cmn.xml
Labels: Component: Core Schema

#1418 guidelines: enhance `@place` documentation for `<dynam>`
  source/docs/04-cmn.xml
  source/examples/cmn/cmn-sample129.txt
Labels: Component: Guidelines & Documentation

#1378 guidelines: fix documentation for optimize
  source/modules/MEI.shared.xml
Labels: Component: Core Schema, Priority: Medium, Backwards-Compatibility: breaking, Status: Needs Review, Type: Bugfix

#1410 utils: fix element descriptions in guidelines ref
  utils/guidelines_xslt/odd2html/generateWebsite.xsl
  utils/guidelines_xslt/odd2html/guidelines.xsl
Labels: Component: Utils

#1424 schema: fix missing scheme attributes in gi elements
  source/docs/13-linkingdata.xml
  source/modules/MEI.cmn.xml
Labels: Component: Guidelines & Documentation, Component: Core Schema, Status: Ready To Merge, Type: Bugfix

#1425 validation: avoid shadowed schematron context in mei-source.sch
  source/validation/mei-source.sch
Labels: Component: Validation

#1407 docs: fix documentation for MIDI values
  source/modules/MEI.midi.xml
Labels: Component: Core Schema
