Repository music-encoding/music-encoding, pull requests merged in 2024-03, with the labels that each got.

#1436 guidelines: update neumes-sample-6-04-04.txt
  source/examples/neumes/neumes-sample-6-04-04.txt
Labels: Component: Guidelines & Documentation

#1432 guidelines: fix display of example encoding
  source/examples/verovio/04-score-redefinition.mei
Labels: Component: Guidelines & Documentation, Status: Needs Review

#1426 guidelines: fix chapter 13
  source/docs/13-linkingdata.xml
  source/examples/linkalign/linkalign-example023.txt
  source/examples/verovio/att-corresp.mei
Labels: Component: Guidelines & Documentation, Status: Ready To Merge

#1422 customizations: fix basic customization
  customizations/mei-basic.xml
Labels: Status: Needs Review, Type: Bugfix, Component: Customizations

#1352 schema: revise description of <catRel>
  source/modules/MEI.header.xml
Labels: Component: Core Schema

#1417 guidelines: tag composer names in Guidelines
  source/docs/04-cmn.xml
  source/docs/08-lyricsperfdir.xml
Labels: Component: Guidelines & Documentation
