Repository music-encoding/music-encoding, pull requests merged in 2024-10, with the labels that each got.

#1534 customizations: add `@tab.anchorline`, document GLT vertical alignment
  source/assets/images/modules/tablature/tab-anchorline-2.png
  source/assets/images/modules/tablature/tab-anchorline.png
  source/assets/images/modules/tablature/tab-bottom-aligned.png
  source/assets/images/modules/tablature/tab-irregularly-aligned.png
  source/assets/images/modules/tablature/tab-top-aligned.png
  source/docs/07-tablature.xml
  source/examples/tablature/tablature-sample004.txt
  source/examples/tablature/tablature-sample012.txt
  source/examples/tablature/tablature-sample013.txt
  source/examples/tablature/tablature-sample014.txt
  source/examples/tablature/tablature-sample015.txt
  source/examples/tablature/tablature-sample016.txt
  source/examples/tablature/tablature-sample017.txt
  source/modules/MEI.stringtab.xml
Labels: Component: Guidelines & Documentation, Component: Core Schema, Component: Images

#1520 docs: remove misleading regex
  source/modules/MEI.stringtab.xml
  source/modules/MEI.xml
Labels: Component: Core Schema

#1503 schema: unify remarks
  source/modules/MEI.cmn.xml
  source/modules/MEI.critapp.xml
  source/modules/MEI.drama.xml
  source/modules/MEI.edittrans.xml
  source/modules/MEI.facsimile.xml
  source/modules/MEI.figtable.xml
  source/modules/MEI.header.xml
  source/modules/MEI.namesdates.xml
  source/modules/MEI.ptrref.xml
  source/modules/MEI.text.xml
Labels: Component: Core Schema

#1492 guidelines: clarify use of page/system/line beginnings
  source/docs/02-shared.xml
  source/docs/03-metadata.xml
  source/docs/08-lyricsperfdir.xml
  source/docs/09-textencoding.xml
  source/docs/13-linkingdata.xml
Labels: Component: Guidelines & Documentation

#1506 guidelines: give credit to main editor of chapter 3
  source/docs/03-metadata.xml
Labels: Component: Guidelines & Documentation

#1538 docs: refine multiRest description
  source/modules/MEI.cmn.xml
Labels: Component: Core Schema

#1537 docs: remove regex from description
  source/modules/MEI.xml
Labels: Component: Core Schema
