Repository music-encoding/music-encoding, pull requests merged in 2024-12, with the labels that each got.

#1563 validation: improve message formatting
  source/validation/mei-source.sch
Labels: Component: Validation

#1567 guidelines: insert fallen out div at the end of chapter 3.3 (II)
  source/docs/03-metadata.xml
Labels: Component: Guidelines & Documentation

#1558 schema: simplify meterSigGrp model
  source/modules/MEI.cmn.xml
Labels: Component: Core Schema

#1560 guidelines: bring back documentation about names and dates
  source/docs/09-textencoding.xml
  source/examples/namesDates/namesDates-corpName1.txt
  source/examples/namesDates/namesDates-corpName2.txt
  source/examples/namesDates/namesDates-corpName3.txt
  source/examples/namesDates/namesDates-geogName1.txt
  source/examples/namesDates/namesDates-geogName2.txt
  source/examples/namesDates/namesDates-geogName3.txt
  source/examples/namesDates/namesDates-geogName4.txt
  source/examples/namesDates/namesDates-geogName5.txt
  source/examples/namesDates/namesDates-geogName6.txt
  source/examples/namesDates/namesDates-geogName7.txt
  source/examples/namesDates/namesDates-geogName8.txt
  source/examples/namesDates/namesDates-name_type.txt
  source/examples/namesDates/namesDates-periodName1.txt
  source/examples/namesDates/namesDates-periodName2.txt
  source/examples/namesDates/namesDates-periodName3.txt
  source/examples/namesDates/namesDates-persName1.txt
  source/examples/namesDates/namesDates-persName2.txt
  source/examples/namesDates/namesDates-persName3.txt
  source/examples/namesDates/namesDates-persName4.txt
  source/examples/namesDates/namesDates-persName5.txt
  source/examples/namesDates/namesDates-persName6.txt
  source/examples/namesDates/namesDates-persName7.txt
  source/examples/namesDates/namesDates-styleName1.txt
  source/examples/namesDates/namesDates-styleName2.txt
  source/examples/namesDates/namesDates-styleName3.txt
Labels: Component: Guidelines & Documentation

#1569 schema: extract data class for harp pedal position
  source/modules/MEI.cmn.xml
Labels: Component: Core Schema

#1555 schema: remove defaultVal from meiversion attributes
  customizations/mei-CMN.xml
  customizations/mei-Mensural.xml
  customizations/mei-Neumes.xml
  customizations/mei-all.xml
  customizations/mei-all_anyStart.xml
  customizations/mei-basic.xml
  source/mei-source.xml
  source/modules/MEI.shared.xml
  utils/compare_versions/comparison.xsl
  utils/guidelines_xslt/odd2html.xsl
Labels: Component: Core Schema, Component: Utils, Component: Customizations

#1557 schema: add unspecified as value for bracket spans
  source/modules/MEI.cmn.xml
Labels: Component: Core Schema
