Repository music-encoding/music-encoding, pull requests merged in 2024-09, with the labels that each got.

#1533 docs: remove copyright dates
  README.md
  build.xml
  customizations/mei-CMN.xml
  customizations/mei-Mensural.xml
  customizations/mei-Neumes.xml
  customizations/mei-all.xml
  customizations/mei-all_anyStart.xml
  customizations/mei-basic.xml
  source/docs/01-introduction.xml
  source/docs/02-shared.xml
  source/docs/03-metadata.xml
  source/docs/04-cmn.xml
  source/docs/05-mensural.xml
  source/docs/06-neumes.xml
  source/docs/07-tablature.xml
  source/docs/08-lyricsperfdir.xml
  source/docs/09-textencoding.xml
  source/docs/10-analysisharm.xml
  source/docs/11-scholarlyediting.xml
  source/docs/12-facsimilesrecordings.xml
  source/docs/13-linkingdata.xml
  source/docs/14-integration.xml
  source/mei-source.xml
  source/modules/MEI.analytical.xml
  source/modules/MEI.cmn.xml
  source/modules/MEI.cmnOrnaments.xml
  source/modules/MEI.corpus.xml
  source/modules/MEI.critapp.xml
  source/modules/MEI.drama.xml
  source/modules/MEI.edittrans.xml
  source/modules/MEI.externalsymbols.xml
  source/modules/MEI.facsimile.xml
  source/modules/MEI.figtable.xml
  source/modules/MEI.fingering.xml
  source/modules/MEI.frbr.xml
  source/modules/MEI.genetic.xml
  source/modules/MEI.gestural.xml
  source/modules/MEI.harmony.xml
  source/modules/MEI.header.xml
  source/modules/MEI.lyrics.xml
  source/modules/MEI.mensural.xml
  source/modules/MEI.midi.xml
  source/modules/MEI.msDesc.xml
  source/modules/MEI.namesdates.xml
  source/modules/MEI.neumes.xml
  source/modules/MEI.performance.xml
  source/modules/MEI.ptrref.xml
  source/modules/MEI.shared.xml
  source/modules/MEI.stringtab.xml
  source/modules/MEI.text.xml
  source/modules/MEI.usersymbols.xml
  source/modules/MEI.visual.xml
  source/modules/MEI.xml
Labels: Component: Guidelines & Documentation, Component: Core Schema, Component: Customizations, Component: Build

#1528 schema: remove `@versionDate`
  source/modules/MEI.analytical.xml
  source/modules/MEI.cmn.xml
  source/modules/MEI.cmnOrnaments.xml
  source/modules/MEI.corpus.xml
  source/modules/MEI.critapp.xml
  source/modules/MEI.drama.xml
  source/modules/MEI.edittrans.xml
  source/modules/MEI.facsimile.xml
  source/modules/MEI.figtable.xml
  source/modules/MEI.fingering.xml
  source/modules/MEI.genetic.xml
  source/modules/MEI.gestural.xml
  source/modules/MEI.harmony.xml
  source/modules/MEI.header.xml
  source/modules/MEI.mensural.xml
  source/modules/MEI.midi.xml
  source/modules/MEI.msDesc.xml
  source/modules/MEI.namesdates.xml
  source/modules/MEI.neumes.xml
  source/modules/MEI.performance.xml
  source/modules/MEI.ptrref.xml
  source/modules/MEI.shared.xml
  source/modules/MEI.text.xml
  source/modules/MEI.usersymbols.xml
  source/modules/MEI.visual.xml
Labels: Component: Core Schema

#1526 docs: remove contradictory remarks on `<hand>`
  source/modules/MEI.header.xml
Labels: Component: Core Schema

#1527 schema: make q and quote member of att.textRendition
  source/modules/MEI.text.xml
Labels: Component: Core Schema

#1510 utils: update comparison script to work with dataSpec
  utils/compare_versions/comparison.xsl
  utils/compare_versions/resources/js/main.js
Labels: Component: Utils
