Repository music-encoding/music-encoding, pull requests merged in 2024-11, with the labels that each got.

#1541 schema: fix attribution of `@tab.anchorline` and `@tab.align`
  source/modules/MEI.stringtab.xml
  source/modules/MEI.visual.xml
Labels: Component: Core Schema

#1543 schema: make att.course.log member of att.accidental
  source/modules/MEI.stringtab.xml
Labels: Component: Core Schema

#1190 schema: enhance meterSigGrp
  source/docs/04-cmn.xml
  source/examples/verovio/tchaikovsky_scherzo.mei
  source/modules/MEI.cmn.xml
  source/modules/MEI.visual.xml
Labels: Component: Guidelines & Documentation, Component: Core Schema, Type: Feature Request

#1544 build: update stylesheets for build
  BUILD_COMMANDLINE.md
  build.xml
Labels: Component: Build

#1428 build: add schematron validation target
  BUILD_COMMANDLINE.md
  build.xml
Labels: Status: Needs Review, Component: Build

#1552 guidelines: fix tstamp explanation
  source/docs/01-introduction.xml
Labels: Component: Guidelines & Documentation

#1549 build: extract build properties
  BUILD_COMMANDLINE.md
  build.properties
  build.xml
Labels: Component: Build

#1553 schema: refine `data.INTERVAL.HARMONIC`
  source/docs/10-analysisharm.xml
  source/examples/harmony/harmony-sample261.txt
  source/examples/harmony/harmony-sample262.txt
  source/modules/MEI.harmony.xml
  source/modules/MEI.xml
Labels: Component: Guidelines & Documentation, Component: Core Schema

#1556 schema: add usage to attribute definitions
  source/modules/MEI.edittrans.xml
  source/modules/MEI.frbr.xml
  source/modules/MEI.genetic.xml
  source/modules/MEI.gestural.xml
  source/modules/MEI.header.xml
  source/modules/MEI.msDesc.xml
  source/modules/MEI.shared.xml
Labels: Component: Core Schema

#1551 docs: fix description of values in data.COURSETUNING
  source/modules/MEI.stringtab.xml
Labels: Component: Core Schema
