Repository music-encoding/music-encoding, pull requests merged in 2025-02, with the labels that each got.

#1586 schema: replace version 5.1 with 6.0-dev
  build.properties
  customizations/mei-CMN.xml
  customizations/mei-Mensural.xml
  customizations/mei-Neumes.xml
  customizations/mei-all.xml
  customizations/mei-all_anyStart.xml
  customizations/mei-basic.xml
  source/assets/images/meilogo_ascii_100.txt
  source/examples/neumes/neumes-sample169.txt
  source/examples/shared/shared-sample0000.txt
  source/examples/shared/shared-sample0001.txt
  source/examples/shared/shared-sample0002.txt
  source/examples/shared/shared-sample0003.txt
  source/examples/svg/svg-example.xml
  source/examples/verovio/04-score-redefinition.mei
  source/examples/verovio/accid-03.mei
  source/examples/verovio/alteration.mei
  source/examples/verovio/ars_antiqua.mei
  source/examples/verovio/att-corresp.mei
  source/examples/verovio/augmentation.mei
  source/examples/verovio/editorial_example.mei
  source/examples/verovio/imperfection.mei
  source/examples/verovio/implicit-mensuration.mei
  source/examples/verovio/mensuration_changes.mei
  source/examples/verovio/motet_fauvel_fol22r_triplum.mei
  source/examples/verovio/notes_rests.mei
  source/examples/verovio/octave-shift-01.mei
  source/examples/verovio/partial-imp-01-propinquam.mei
  source/examples/verovio/partial-imp-02-bilateral.mei
  source/examples/verovio/partial-imp-03-remotam.mei
  source/examples/verovio/partial-imp-04-remotam.mei
  source/examples/verovio/tchaikovsky_scherzo.mei
  source/examples/verovio/tempo-01.mei
  source/mei-source.xml
  source/modules/MEI.shared.xml
Labels: Component: Guidelines & Documentation, Component: Core Schema, Component: Customizations, Component: Images

#1591 build: add validation on PR
  .github/workflows/deploy.yml
  .github/workflows/pr-validation.yml
Labels: Component: Workflows

#1614 guidelines: add missing link for `<fileDesc>` in chapter 3
  source/docs/03-metadata.xml
Labels: Component: Guidelines & Documentation

#1615 guidelines: add specList for front and back to chapter 9
  source/docs/09-textencoding.xml
Labels: Component: Guidelines & Documentation

#1616 guidelines: correct misleading filename, id and title of chapter 12
  source/docs/12-facsimilesperformances.xml
  source/mei-source.xml
Labels: Component: Guidelines & Documentation, Component: Core Schema

#1621 patch: remove prefix in `develop-monogr`
  source/modules/MEI.shared.xml
Labels: Component: Core Schema

#1628 docs: clarify use of dur.ges
  source/modules/MEI.gestural.xml
Labels: Component: Core Schema

#1624 schema: clean up rng:choices with one element
  source/modules/MEI.edittrans.xml
  source/modules/MEI.figtable.xml
  source/modules/MEI.header.xml
  source/modules/MEI.shared.xml
  source/modules/MEI.text.xml
  source/modules/MEI.xml
Labels: Component: Core Schema

#1627 patch: develop-profileDescPart
  source/docs/03-metadata.xml
  source/examples/header/header-sample080.txt
  source/modules/MEI.shared.xml
Labels: Component: Guidelines & Documentation, Component: Core Schema

#1639 schema: remove dur.visible
  source/modules/MEI.visual.xml
Labels: Component: Core Schema

#1629 patch: develop-relax-frbr
  source/docs/03-metadata.xml
  source/modules/MEI.frbr.xml
Labels: Component: Guidelines & Documentation, Component: Core Schema

#1641 guidelines: update example to verovio
  source/docs/04-cmn.xml
  source/examples/cmn/cmn-sample162.txt
  source/examples/verovio/mRpt-01.mei
Labels: Component: Guidelines & Documentation

#1645 utils: fix rendering of lists
  utils/guidelines_xslt/odd2html/guidelines.xsl
Labels: Component: Utils

#1636 schema: remove tuplet specifics in description of att.numberPlacement
  source/modules/MEI.cmn.xml
Labels: Component: Core Schema

#1625 guidelines: supplement quotation chapter
  source/docs/09-textencoding.xml
  source/examples/text/text-sample365.txt
Labels: Component: Guidelines & Documentation

#1622 guidelines: add specs for glyph attributes to `9.2.2 Text Rendition`
  source/docs/09-textencoding.xml
Labels: Component: Guidelines & Documentation

#1649 guidelines: fix eof in example files
  source/docs/07-tablature.xml
  source/examples/verovio/04-score-redefinition.mei
  source/examples/verovio/accid-03.mei
  source/examples/verovio/alteration.mei
  source/examples/verovio/ars_antiqua.mei
  source/examples/verovio/att-corresp.mei
  source/examples/verovio/augmentation.mei
  source/examples/verovio/editorial_example.mei
  source/examples/verovio/imperfection.mei
  source/examples/verovio/implicit-mensuration.mei
  source/examples/verovio/mRpt-01.mei
  source/examples/verovio/mensuration_changes.mei
  source/examples/verovio/motet_fauvel_fol22r_triplum.mei
  source/examples/verovio/notes_rests.mei
  source/examples/verovio/octave-shift-01.mei
  source/examples/verovio/partial-imp-01-propinquam.mei
  source/examples/verovio/partial-imp-02-bilateral.mei
  source/examples/verovio/partial-imp-03-remotam.mei
  source/examples/verovio/partial-imp-04-remotam.mei
  source/examples/verovio/tchaikovsky_scherzo.mei
  source/examples/verovio/tempo-01.mei
Labels: Component: Guidelines & Documentation

#1611 schema: tidying up tablature schema
  source/modules/MEI.stringtab.xml
Labels: Component: Core Schema
