Repository music-encoding/music-encoding, pull requests merged in 2025-03, with the labels that each got.

#1355 schema: restrict content model of `<editor>`
  source/modules/MEI.shared.xml
Labels: Component: Core Schema

#1513 schema: align method attribute with TEI
  source/modules/MEI.header.xml
Labels: Component: Core Schema

#1635 guidelines: add captions to verovio and listings for chapter 1–3
  source/docs/01-introduction.xml
  source/docs/02-shared.xml
  source/docs/03-metadata.xml
Labels: Component: Guidelines & Documentation

#1653 guidelines: fix tablature examples dots
  source/examples/tablature/tablature-sample016.txt
  source/examples/tablature/tablature-sample017.txt
Labels: Component: Guidelines & Documentation

#1654 guidelines: fix ossia section
  source/docs/04-cmn.xml
  source/examples/cmn/cmn-ossia_layer.txt
  source/examples/cmn/cmn-ossia_staff.txt
Labels: Component: Guidelines & Documentation

#1361 schema: remove watermark's membership in msInline
  source/modules/MEI.header.xml
Labels: Component: Core Schema

#1365 schema: revise model of `<respStmt>`
  source/modules/MEI.shared.xml
Labels: Component: Core Schema

#1632 schema: develop watermark (Step 1)
  source/docs/03-metadata.xml
  source/modules/MEI.header.xml
  source/modules/MEI.shared.xml
Labels: Component: Guidelines & Documentation, Component: Core Schema

#1634 utils: fix example images being created with the wrong suffix
  utils/guidelines_xslt/odd2html/guidelines.xsl
Labels: Component: Utils

#1364 schema: modify content model of monogr
  source/modules/MEI.shared.xml
Labels: Component: Core Schema

#1608 docs: use latest TEI version
  source/docs/01-introduction.xml
  source/docs/02-shared.xml
  source/docs/03-metadata.xml
  source/docs/04-cmn.xml
  source/docs/05-mensural.xml
  source/docs/06-neumes.xml
  source/docs/07-tablature.xml
  source/docs/08-lyricsperfdir.xml
  source/docs/09-textencoding.xml
  source/docs/10-analysisharm.xml
  source/docs/11-scholarlyediting.xml
  source/docs/12-facsimilesperformances.xml
  source/docs/13-linkingdata.xml
  source/docs/14-integration.xml
Labels: Component: Guidelines & Documentation
